UVote/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UVote.Models;

namespace UVote.Controllers
{
    public class AdminController : Controller
    {
        DAO dao = new DAO();

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        // GET: Login
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        // POST: Login
        [HttpPost]
        public ActionResult Login(AdminModel admin)
        {
            ModelState.Remove("EmployeeId");
            ModelState.Remove("Name");

            if (ModelState.IsValid)
            {
                admin.EmployeeId = dao.AdminLogin(admin);
                if (admin.EmployeeId != null)
                {
                    Session["employeeId"] = admin.EmployeeId;
                    //Session["name"] = admin.Name;
                    //ViewBag.Session = Session["employeeId"] + "" + Session["name"];
                    ViewBag.Session = Session["employeeId"];
                    return View("Index");
                }
                else
                {
                    ViewBag.Message = $"Error {dao.message}!";
                    return View("Error");
                }
            }
            else return View(admin);
        }

        // Logout
        public ActionResult Logout()
        {
            return View();
        }

        // Create admin
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(AdminModel adminModel)
        {
            int count = 0;
            if (ModelState.IsValid)
            {
                count = dao.InsertAdmin(adminModel);
                if (count == 1)
                {
                    ViewBag.Message = "Admin created!";
                    return View("Success");
                }
                else
                {
                    ViewBag.Message = $"Error {dao.message}!";
                    return View("Error");
                }   
            }
            return View(adminModel);
        }
    }
}

UVote/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UVote.Models;

namespace UVote.Controllers
{
    public class StudentController : Controller
    {
        // DAO instance
        DAO dao = new DAO();

        // GET: Student
        public ActionResult Index()
        {
            return View();
        }

        // GET: Student/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Student/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Student/Create
        [HttpPost]
        public ActionResult Create(StudentModel studentModel)
        {
            int count = 0;
            if (ModelState.IsValid)
            {
                count = dao.Insert(studentModel);
                if (count == 1)
                {
                    ViewBag.Message = "New student added!";
                    return View("Success");
                }
                else
                {
                    ViewBag.Message = $"Error {dao.message}!";
                    return View("Error");
                }           
            }
            return View(studentModel);
        }

        // GET: Student/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Student/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Student/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UVote/Controllers/VoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UVote.Controllers
{
    public class VoteController : Controller
    {
        // GET: Vote
        public ActionResult Index()
        {
            return View();
        }

        // GET: Vote/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Vote/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vote/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vote/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Vote/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vote/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Vote/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UVote/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/StylesSheet.css" type="text/css" />
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-collapse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("uVote", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("FAQ", "FAQ", "Home")</li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li>@{Html.RenderPartial("_LoginRegister"); }</li>
                    </ul>

                </div>
            </div>
        </nav>

        <div class="container">
            @RenderSection("Logged", false)
            @RenderBody()
            
                <footer class="footer">
                    <div class="container">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Sitemap", "Sitemap", "Home")</li>
                            <li><a href="#">IT support</a></li>
                            <li><a href="#">HR</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Library</a></li>
                            <li><a href="#">IT support</a></li>
                        </ul>
                    </div>
                </footer>
               
           
        </div>
        <script src="~/Scripts/jquery-3.1.1.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
    </div>
</body>
</html>

UVote/Views/Shared/_LoginRegister.cshtml
@if (Session["employeeId"] != null)
{
    @Html.ActionLink("Logout", "Logout", "Admin")
}
else if (Session["studentNumber"] != null)
{
    @Html.ActionLink("Logout", "Logout", "Vote")
}
else
{
    <li>@Html.ActionLink("Admin", "Login", "Admin")</li>
    <li>@Html.ActionLink("Vote", "Login", "Student")</li>
}