UVote/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UVote.Models;

namespace UVote.Controllers
{
    public class AdminController : Controller
    {
        DAO dao = new DAO();

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        // GET: Login
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        // POST: Login
        [HttpPost]
        public ActionResult Login(AdminModel admin)
        {
            ModelState.Remove("EmployeeId");
            ModelState.Remove("Name");

            if (ModelState.IsValid)
            {
                admin.EmployeeId = dao.AdminLogin(admin);
                if (admin.EmployeeId != null)
                {
                    Session["employeeId"] = admin.EmployeeId;
                    //Session["name"] = admin.Name;
                    //ViewBag.Session = Session["employeeId"] + "" + Session["name"];
                    ViewBag.Session = Session["employeeId"];
                    return View("Index");
                }
                else
                {
                    ViewBag.Message = $"Error {dao.message}!";
                    return View("Error");
                }
            }
            else return View(admin);
        }

        // Logout
        public ActionResult Logout()
        {
            return View();
        }

        // Create admin
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(AdminModel adminModel)
        {
            int count = 0;
            if (ModelState.IsValid)
            {
                count = dao.InsertAdmin(adminModel);
                if (count == 1)
                {
                    ViewBag.Message = "Admin created!";
                    return View("Success");
                }
                else
                {
                    ViewBag.Message = $"Error {dao.message}!";
                    return View("Error");
                }   
            }
            return View(adminModel);
        }
    }
}

UVote/Controllers/CampaignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UVote.Models;

namespace UVote.Controllers
{
    public class CampaignController : Controller
    {
        DAO dao = new DAO();

        // GET: Campaign
        public ActionResult Index()
        {
            return View();
        }

        // GET: Campaign/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Campaign/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Campaign/Create
        [HttpPost]
        public ActionResult Create(CampaignModel campaignModel)
        {
            int count = 0;
            if (ModelState.IsValid)
            {
                count = dao.InsertCampaign(campaignModel);
                if (count == 1)
                {
                    ViewBag.Message = "Campaign created!";
                    return View("Success");
                }
                else
                {
                    ViewBag.Message = $"Error {dao.message}!";
                    return View("Error");
                }
            }
            return View(campaignModel);
        }

        // GET: Campaign/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Campaign/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Campaign/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Campaign/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UVote/Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UVote.Models;

namespace UVote.Controllers
{
   
    public class CandidateController : Controller
    {
        DAO dao = new DAO();

        // GET: Candidate
        public ActionResult Index()
        {
            return View();
        }

        // GET: Candidate/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Candidate/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Candidate/Create
        [HttpPost]
        public ActionResult Create(CandidateModel candidateModel)
        {
            int count = 0;

            if(ModelState.IsValid)
            {
                count = dao.InsertCandidate(candidateModel);
                if (count == 1)
                {
                    ViewBag.Message = "Candidates Added";
                    return View("Success");
                }
                else
                {
                    ViewBag.Message = $"Error {dao.message}!";
                    return View("Error");
                }
            }
            
                return View(candidateModel);
            
        }

        // GET: Candidate/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Candidate/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Candidate/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Candidate/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UVote/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UVote.Models;

namespace UVote.Controllers
{
    public class StudentController : Controller
    {
        // DAO instance
        DAO dao = new DAO();

        // GET: Student
        public ActionResult Index()
        {
            return View();
        }

        // GET: Student/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Student/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Student/Create
        [HttpPost]
        public ActionResult Create(StudentModel studentModel)
        {
            int count = 0;
            if (ModelState.IsValid)
            {
                count = dao.Insert(studentModel);
                if (count == 1)
                {
                    ViewBag.Message = "New student added!";
                    return View("Success");
                }
                else
                {
                    ViewBag.Message = $"Error {dao.message}!";
                    return View("Error");
                }           
            }
            return View(studentModel);
        }

        // GET: Student/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Student/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Student/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UVote/Views/Admin/Create.cshtml
@model UVote.Models.AdminModel
@{
    ViewBag.Title = "Create admin";
}

<h2>Create admin</h2>
@using (Html.BeginForm("Create", "Admin", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EmployeeId)
                @Html.ValidationMessageFor(model => model.EmployeeId, "", htmlAttributes: new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name, "", htmlAttributes: new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email, "", htmlAttributes: new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password, "", htmlAttributes: new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10 col-md-offest-2">
                <input type="submit" name="submit" value="Submit" />
                <input type="reset" name="reset" value="Reset" />
            </div>
        </div>

    </div>
}

UVote/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2> <!--This is Admin Index-->

<div class="col-md-4">
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="active">@Html.ActionLink("Add campaign", "Create", "Campaign")</li>
        <li role="presentation">@Html.ActionLink("Add candidate", "Create", "Candidate")</li>
        <li role="presentation">@Html.ActionLink("Add student", "Create", "Student")</li>
    </ul>
</div>


<div class="col-md-4">
        <a href="/Campaign/Index" class="thumbnail">
        <img src="~/Content/Images/ActiveCampaignsOrangeSquare.png" alt="Active Campaigns">
        </a>
</div>

<div class="col-md-4">
    <a href="/Candidate/Index" class="thumbnail">
        <img src="~/Content/Images/CandidateOrangeSquare.jpg" alt="List of Candidates">
    </a>
</div>

<div id="penguin">
    <div class="col-md-4">
        <a href="#">
            <img src="~/Content/Images/penguinAdmin.png" alt="Admin penguin cartoon" width="200" height="200" />
        </a>
    </div>
</div>

UVote/Views/Admin/Login.cshtml
@model UVote.Models.AdminModel
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
@using (Html.BeginForm("Login", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
{

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", htmlAttributes: new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", htmlAttributes: new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2 col-md-offset-2">
                <input type="submit" name="submit" class="btn btn-primary" value="Login" />
            </div>
        </div>
    
}

UVote/Views/Admin/Logout.cshtml
@{
    ViewBag.Title = "Logout";
}

<h2>Logout</h2>

UVote/Views/Admin/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>@ViewBag.Message</strong>@Html.ActionLink("Add another", "Create", "Admin")..
</div>